Algoritmo "Enquanto"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

   Nomes: Vetor[0..4] de Caractere
   I: Inteiro
Inicio

   Nomes[0] <- "Joao"
   Nomes[1] <- "Maria
   Nomes[2] <- "Jose"
   Nomes[3] <- "Ana"
   Nomes[4] <- "Jorge"
   
   I <- 0
   Enquanto I < 5 Faca
      Escreval(Nomes[I])
      I <- I + 1
   FimEnquanto
   


Fimalgoritmo