Algoritmo "MediaNotas"

Var
       Nota1, Nota2, Nota3, Nota4, Resultado: Real


Inicio

      Escreva("Digite a primeira nota: ")
      Leia(Nota1)
      Escreva("Digite a segunda nota: ")
      Leia(Nota2)
      Escreva("Digite a terceira nota: ")
      Leia(Nota3)
      Escreva("Digite a quarta nota: ")
      Leia(Nota4)
      
      Resultado <- (Nota1 + Nota2 + Nota3 + Nota4) / 4
      
      Escreva("A média é: ", Resultado)
      
Fimalgoritmo