Algoritmo "Variaveis"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

   Abacate, Melancia, TotalFrutasSacola : Inteiro

Inicio
      // declarando variaveis
      Abacate <- 2
      Melancia <- 3
      // declaracao variavel da soma
      TotalFrutasSacola <- Abacate + Melancia
      
      Abacate <- 5
      TotalFrutasSacola <- Abacate + Melancia
      Escreva("Total de Frutas na sacola", TotalFrutasSacola)

Fimalgoritmo